version: '3.1'

services:

   tomcat-server:
      image: library-tomcat:8.5.47
      ports:
         - "8080"
      links:
         - "mysql-server:mysql"
      deploy:
         replicas: 2
   mysql-server:
      image: mysql:5.7.28
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: mysql
      ports:
         - "3307:3306"